services:
  pybay_image:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: pybay_image
    volumes:
      - .:/code
    working_dir: /code
    entrypoint: ["sleep", "infinity"]
