services:
  pybay_image:
    container_name: pybay_image
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/code
    working_dir: /code
    entrypoint: ["sleep", "infinity"]
